version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - "27017:27017"  # MongoDB typically runs on port 27017, not 5432
    volumes:
      - mongodb-data:/data/db
    networks:
      - shared-network

  front-end:
    container_name: front-end-react
    restart: unless-stopped
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:8448"
    networks:
      - shared-network
    depends_on:
      - mongodb

  back-end:
    container_name: back-end-users
    restart: unless-stopped
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "4000:1188"  # Adjusted to reflect your earlier description (4000 external, 1188 internal)
    networks:
      - shared-network
    depends_on:
      - mongodb

networks:
  shared-network:

volumes:
  mongodb-data:
