version: '3.9'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network
  front-end:
    container_name: front-end-react
    restart: unless-stopped
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8448:3000"
    networks:
      - app-network

  edit-view-run-ms:
    container_name: edit-view-run-ms
    restart: unless-stopped
    build:
      context: ./edit-view-run-ms
      dockerfile: Dockerfile
    ports:
      - "4000:7000"
    env_file:
      - ./edit-view-run-ms/.env
    networks:
      - app-network

  login-ms:
    container_name: login-ms
    restart: unless-stopped
    build:
      context: ./login-ms
      dockerfile: Dockerfile
    ports:
      - "4001:7001"
    env_file:
      - ./login-ms/.env
    depends_on:
      - rabbitmq
    networks:
      - app-network

  view-results-ms:
    container_name: view-results-ms
    restart: unless-stopped
    build:
      context: ./view-results-ms
      dockerfile: Dockerfile
    ports:
      - "4002:7002"
    env_file:
      - ./view-results-ms/.env
    networks:
      - app-network
    
  solver-ms:
    container_name: solver-ms
    restart: unless-stopped
    build:
      context: ./solver-ms
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network
      
volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge