version: '3.9'

services:
  front-end:
    container_name: front-end-react
    restart: unless-stopped
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8448:3000"
    networks:
      - app-network

  edit-view-run-ms:
    container_name: edit-view-run-ms
    build:
      context: ./edit-view-run-ms
      dockerfile: Dockerfile
    ports:
      - "4000:7000"
    env_file:
      - ./edit-view-run-ms/.env
    networks:
      - app-network

  login-ms:
    container_name: login-ms
    build:
      context: ./login-ms
      dockerfile: Dockerfile
    ports:
      - "4001:7001"
    env_file:
      - ./login-ms/.env
    networks:
      - app-network

  view-results-ms:
    container_name: view-results-ms
    build:
      context: ./view-results-ms
      dockerfile: Dockerfile
    ports:
      - "4002:7002"
    env_file:
      - ./view-results-ms/.env
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge